/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator;

/**
 *
 * @author s
 */
public class cal extends javax.swing.JFrame {

    /**
     * Creates new form cal
     */
    public cal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ibHienthi = new javax.swing.JLabel();
        nhan = new javax.swing.JPanel();
        So7 = new javax.swing.JButton();
        So8 = new javax.swing.JButton();
        So9 = new javax.swing.JButton();
        chia = new javax.swing.JButton();
        So4 = new javax.swing.JButton();
        So5 = new javax.swing.JButton();
        So6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        So1 = new javax.swing.JButton();
        So2 = new javax.swing.JButton();
        So3 = new javax.swing.JButton();
        tru = new javax.swing.JButton();
        xoa = new javax.swing.JButton();
        So0 = new javax.swing.JButton();
        bang = new javax.swing.JButton();
        cong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ibHienthi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ibHienthi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ibHienthi.setText("0");

        nhan.setLayout(new java.awt.GridLayout(4, 4, 2, 2));

        So7.setText("7");
        So7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So7ActionPerformed(evt);
            }
        });
        nhan.add(So7);

        So8.setText("8");
        So8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So8ActionPerformed(evt);
            }
        });
        nhan.add(So8);

        So9.setText("9");
        So9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So9ActionPerformed(evt);
            }
        });
        nhan.add(So9);

        chia.setText("/");
        chia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chiaActionPerformed(evt);
            }
        });
        nhan.add(chia);

        So4.setText("4");
        So4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So4ActionPerformed(evt);
            }
        });
        nhan.add(So4);

        So5.setText("5");
        So5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So5ActionPerformed(evt);
            }
        });
        nhan.add(So5);

        So6.setText("6");
        So6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So6ActionPerformed(evt);
            }
        });
        nhan.add(So6);

        jButton9.setText("*");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        nhan.add(jButton9);

        So1.setText("1");
        So1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So1ActionPerformed(evt);
            }
        });
        nhan.add(So1);

        So2.setText("2");
        So2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So2ActionPerformed(evt);
            }
        });
        nhan.add(So2);

        So3.setText("3");
        So3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So3ActionPerformed(evt);
            }
        });
        nhan.add(So3);

        tru.setText("-");
        tru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truActionPerformed(evt);
            }
        });
        nhan.add(tru);

        xoa.setText("C");
        xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaActionPerformed(evt);
            }
        });
        nhan.add(xoa);

        So0.setText("0");
        nhan.add(So0);

        bang.setText("=");
        bang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangActionPerformed(evt);
            }
        });
        nhan.add(bang);

        cong.setText("+");
        cong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                congActionPerformed(evt);
            }
        });
        nhan.add(cong);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ibHienthi)
                .addGap(31, 31, 31))
            .addComponent(nhan, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(ibHienthi)
                .addGap(29, 29, 29)
                .addComponent(nhan, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void So8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So8ActionPerformed
        String gtri = this.ibHienthi.getText();
        if (gtri.equals("0")) gtri="";
        this.ibHienthi.setText(gtri + So8.getText());// TODO add your handling code here:
    }//GEN-LAST:event_So8ActionPerformed

    private void chiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chiaActionPerformed
        tinh();
        this.phepToan= "/";
        ibHienthi.setText("0");// TODO add your handling code here:
    }//GEN-LAST:event_chiaActionPerformed

    private void So1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So1ActionPerformed
        String gtri = this.ibHienthi.getText();
        if (gtri.equals("0")) gtri="";
        this.ibHienthi.setText(gtri + So1.getText());
// TODO add your handling code here:
    }//GEN-LAST:event_So1ActionPerformed

    private void So2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So2ActionPerformed
         String gtri = this.ibHienthi.getText();
        if (gtri.equals("0")) gtri="";
        this.ibHienthi.setText(gtri + So2.getText());
// TODO add your handling code here:
    }//GEN-LAST:event_So2ActionPerformed

    private void So3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So3ActionPerformed
        String gtri = this.ibHienthi.getText();
        if (gtri.equals("0")) gtri="";
        this.ibHienthi.setText(gtri + So3.getText());
// TODO add your handling code here:
    }//GEN-LAST:event_So3ActionPerformed

    private void So4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So4ActionPerformed
        String gtri = this.ibHienthi.getText();
        if (gtri.equals("0")) gtri="";
        this.ibHienthi.setText(gtri + So4.getText());// TODO add your handling code here:
    }//GEN-LAST:event_So4ActionPerformed

    private void So5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So5ActionPerformed
        String gtri = this.ibHienthi.getText();
        if (gtri.equals("0")) gtri="";
        this.ibHienthi.setText(gtri + So5.getText());// TODO add your handling code here:
    }//GEN-LAST:event_So5ActionPerformed

    private void So6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So6ActionPerformed
        String gtri = this.ibHienthi.getText();
        if (gtri.equals("0")) gtri="";
        this.ibHienthi.setText(gtri + So6.getText());// TODO add your handling code here:
    }//GEN-LAST:event_So6ActionPerformed

    private void So7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So7ActionPerformed
        String gtri = this.ibHienthi.getText();
        if (gtri.equals("0")) gtri="";
        this.ibHienthi.setText(gtri + So7.getText());// TODO add your handling code here:
    }//GEN-LAST:event_So7ActionPerformed

    private void So9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So9ActionPerformed
         String gtri = this.ibHienthi.getText();
        if (gtri.equals("0")) gtri="";
        this.ibHienthi.setText(gtri + So9.getText());// TODO add your handling code here:
    }//GEN-LAST:event_So9ActionPerformed

    private void congActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_congActionPerformed
        tinh();
        this.phepToan= "+";
        ibHienthi.setText("0");// TODO add your handling code here:
    }//GEN-LAST:event_congActionPerformed

    private void truActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truActionPerformed
        tinh();
        this.phepToan= "-";
        ibHienthi.setText("0");// TODO add your handling code here:
    }//GEN-LAST:event_truActionPerformed

    private void bangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangActionPerformed
        tinh();
        ibHienthi.setText(String.valueOf(this.kq));// TODO add your handling code here:
        this.kq=0;
    }//GEN-LAST:event_bangActionPerformed

    private void xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaActionPerformed
        ibHienthi.setText("0");
        this.phepToan = "";// TODO add your handling code here:
    }//GEN-LAST:event_xoaActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        tinh();
        this.phepToan= "*";
        ibHienthi.setText("0");// TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed
    private long kq=0;
    private String phepToan="";
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton So0;
    private javax.swing.JButton So1;
    private javax.swing.JButton So2;
    private javax.swing.JButton So3;
    private javax.swing.JButton So4;
    private javax.swing.JButton So5;
    private javax.swing.JButton So6;
    private javax.swing.JButton So7;
    private javax.swing.JButton So8;
    private javax.swing.JButton So9;
    private javax.swing.JButton bang;
    private javax.swing.JButton chia;
    private javax.swing.JButton cong;
    private javax.swing.JLabel ibHienthi;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel nhan;
    private javax.swing.JButton tru;
    private javax.swing.JButton xoa;
    // End of variables declaration//GEN-END:variables

    private void tinh() {
        if (this.phepToan.equals("")) this.kq=Long.parseLong(ibHienthi.getText());
        else{
            if (this.phepToan.equals("+")) this.kq += Long.parseLong(ibHienthi.getText());
            if (this.phepToan.equals("-")) this.kq -= Long.parseLong(ibHienthi.getText());
            if (this.phepToan.equals("*")) this.kq *= Long.parseLong(ibHienthi.getText());
            if (this.phepToan.equals("/")) this.kq /= Long.parseLong(ibHienthi.getText());
        }
    }
}
